CREATE DATABASE test;
CREATE USER test@localhost IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON *.* TO test@'%' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON *.* TO test@localhost IDENTIFIED BY 'test';
FLUSH PRIVILEGES;
